name: Java CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:

      - name: Set up repository
        uses: actions/checkout@main
        with:
          ref: master

      - name: Merge to master
        run: git checkout --progress --force ${{ github.sha }}

      # - name: Run repository-wide tests
      #   if: runner.os == 'Linux'
      #   working-directory:  ${{ github.workspace }}/.github
      #   run: ./run-checks.sh

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          java-package: jdk+fx
          cache: gradle

      - name: Setup and test with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: [test, coverage]

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v2
        if: runner.os == 'Linux'
        with:
          directory: ${{ github.workspace }}/build/reports/jacoco/coverage
          files: coverage.xml
          fail_ci_if_error: false
